pipeline:
  info: &info
    image: golang:${GO_VERSION}-alpine
    commands:
      - go version
      - go env
  test:
    << : *info
    commands: go test -v -cover ./...

matrix:
  GO_VERSION:
    - 1.18
    - 1.17

depends_on:
  - dco
